insert into MOVIES (ID,NAME,EXT_ID) values (null, 'The Fast and the Furious','tt0232500')
insert into MOVIES (ID,NAME,EXT_ID) values (null, '2 Fast 2 Furious', 'tt0322259')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'The Fast and the Furious: Tokyo Drift', 'tt0463985')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'Fast & Furious','tt1013752')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'Fast Five', 'tt1596343')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'Fast & Furious 6', 'tt1905041')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'Furious 7', 'tt2820852')
insert into MOVIES (ID,NAME,EXT_ID) values (null, 'The Fate of the Furious','tt4630562')